# Include arguments 
set( CMAKE_INCLUDE_FLAG_RGBDS "-I " )       

# How to assemble/build objects 
set( CMAKE_RGBDS_COMPILE_OBJECT
    # "<CMAKE_RGBDS_COMPILER> <FLAGS> <INCLUDES> -L -o <OBJECT> <SOURCE>"
    "<CMAKE_RGBDS_COMPILER> <INCLUDES> -L -o <OBJECT> <SOURCE>"
)

# How to build executables/ROMs
set( CMAKE_RGBDS_LINK_EXECUTABLE 
    "${CMAKE_RGBDS_LINKER} <LINK_FLAGS> -o <TARGET> <OBJECTS>"
    "${CMAKE_RGBDS_FIXER} -v -p 0xFF <TARGET>"
)


set( CMAKE_RGBDS_INFORMATION_LOADED 1 )


# CMAKE_(LANG)_CREATE_SHARED_LIBRARY
# CMAKE_(LANG)_CREATE_SHARED_MODULE
# CMAKE_(LANG)_CREATE_STATIC_LIBRARY
# CMAKE_(LANG)_COMPILE_OBJECT
# CMAKE_(LANG)_LINK_EXECUTABLE